{
    "name": "BTP SENEGAL",
    "version": "19.0.1.0.0",
    "category": "Construction",
    "summary": "Application BTP Sénégal (chantier, étude de prix, budget) - OHADA-ready",
    "author": "MMLY",
    "license": "OPL-1",
    "depends": [
        "mail",
        "analytic",
        "project",
        "product",
        "uom",
    ],
    "data": [
        "security/btp_security.xml",
        "security/ir.model.access.csv",
        "data/sequence_chantier.xml",
        "data/sequence_devis.xml",
        "data/sequence_budget.xml",
        "data/analytic_plan.xml",
        "views/btp_referentiel_views.xml",
        "views/btp_chantier_views.xml",
        "views/btp_ouvrage_views.xml",
        "views/btp_devis_views.xml",
        "views/btp_budget_views.xml",
        "wizard/devis_to_budget_views.xml",
        "views/btp_menus.xml",
        "views/btp_etude_menus.xml",
        "views/btp_budget_menus.xml",
    ],
    "demo": [
        "demo/demo_base.xml",
        "demo/demo_etude.xml",
        "demo/demo_budget.xml",
    ],
    "application": True,
    "installable": True,
}

